### ISSUE TITLE
Error when displaying Twilio SMS notifications in portal

### ISSUE THREAD

**Issue by LakshayaT** [OsmosysSoftware/osmo-x#200]
**Description:**
We recently added support for Twilio SMS in the api via https://github.com/OsmosysSoftware/osmo-x/pull/180.

However, it looks like currently, we are not handling the displaying of notifications of this channel type in the portal, which causes error displaying notifications.

**Current behaviour:**
On trying to access portal when the database has a notification of `channelType` 5, portal loads partially and shows the below error:

![image](https://github.com/OsmosysSoftware/osmo-x/assets/108812833/10fb78f8-53c7-43a8-a329-9c131399ec5a)

Raw text:
```
ERROR TypeError: Cannot read properties of undefined (reading 'style')
    at NotificationsComponent_p_table_10_ng_template_2_Template (notifications.component.html:59:19)
    at executeTemplate (core.mjs:12003:13)
    at refreshView (core.mjs:13498:13)
    at detectChangesInView (core.mjs:13663:9)
    at detectChangesInEmbeddedViews (core.mjs:13606:13)
    at refreshView (core.mjs:13522:9)
    at detectChangesInView (core.mjs:13663:9)
    at detectChangesInEmbeddedViews (core.mjs:13606:13)
    at refreshView (core.mjs:13522:9)
    at detectChangesInView (core.mjs:13663:9)
```

**Expected behaviour:**
Notifications should be shown correctly without errors in the portal.

**Comment by LakshayaT** [comment]
This has been resolved as part of https://github.com/OsmosysSoftware/osmo-x/pull/232
